version: "3"
services:
  ui-backend:
    image: ${DOCKER_REPO}/${PROJECT_NAME}-ui-backend:1.8.4
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DATABASE_URL: ${DATABASE_IP}
      DATABASE_PORT: ${DATABASE_PORT}
      UI_URL: ${BACKEND_IP}
      UI_PORT: ${UI_PORT}
      K8S_PROMETHEUS_URL: ${K8S_PROMETHEUS_IP}
      K8S_PROMETHEUS_PORT: ${K8S_PROMETHEUS_PORT}
      KUBERNETES_PROVIDER_ENABLE: ${BACKEND_KUBERNETES_PROVIDER_ENABLE}
      KUBERNETES_RESOURCES_ENABLE: ${KUBERNETES_RESOURCES_ENABLE}
      SPRINGDOC_API_DOCS_ENABLED: ${SPRINGDOC_API_DOCS_ENABLED}
      SPRINGDOC_API_DOCS_PATH: ${SPRINGDOC_API_DOCS_PATH}
      SPRINGDOC_API_SWAGGER_UI_ENABLED: ${SPRINGDOC_API_SWAGGER_UI_ENABLED}
      SPRINGDOC_API_SWAGGER_UI_PATH: ${SPRINGDOC_API_SWAGGER_UI_PATH}
      ENABLE_KAFKA: ${BACKEND_ENABLE_KAFKA}
      EXPORTER_URL: ${METRIC_EXPORTER_IP}
      EXPORTER_PORT: ${METRIC_EXPORTER_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATABASE_VOLUME_PATH}:/data
    depends_on:
      - database
    ports:
      - ${BACKEND_PORT}:8080
    restart: always
    network_mode: "host"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    depends_on:
      - database
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: always
    networks:
      maestroDatabaseNetwork:

  #  metric-exporter:
  #    image: ${DOCKER_REPO}/metric-exporter:1.6.0
  #    environment:
  #      KAFKA_URL: ${KAFKA_IP}
  #      KAFKA_PORT: ${KAFKA_PORT}
  #      BACKEND_URL: ${BACKEND_IP}
  #      BACKEND_PORT: ${BACKEND_PORT}
  #      ENABLED_MONITORING: ${METRIC_EXPORTER_ENABLED_MONITORING}
  #      PROMETHEUS_PORT: ${PROMETHEUS_PORT}
  #      PROMETHEUS_URL: ${PROMETHEUS_IP}
  #      CONSUL_URL: ${CONSUL_IP}
  #      CONSUL_PORT: ${CONSUL_HTTP_PORT}
  #    ports:
  #      - ${METRIC_EXPORTER_PORT}:9080
  #    restart: always

  database:
    container_name: "maestro_database"
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ${DATABASE_VOLUME_PATH}:/var/lib/mysql
    restart: always
    networks:
      maestroDatabaseNetwork:

  # knative-controller:
  #   image: knative-serverless-controller:1.0.3
  #   container_name: serverless-controller
  #   restart: unless-stopped
  #   environment:
  #     QUARKUS_HTTP_PORT: ${QUARKUS_HTTP_PORT}
  #     MAESTRO_REST_API_URL: ${MAESTRO_REST_API_URL}
  #     BACKEND_AUTH_SERVER_URL: ${BACKEND_AUTH_SERVER_URL}
  #     BACKEND_CLIENT_ID: ${BACKEND_CLIENT_ID}
  #     BACKEND_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET}
  #     KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     KEYCLOAK_URL: ${KEYCLOAK_URL}
  #     KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
  #     KEYCLOAK_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
  #     KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
  #     KEYCLOAK_ADMIN_CLIENT: ${KEYCLOAK_ADMIN_CLIENT}
  #     KEYCLOAK_ADMIN_REALM: ${KEYCLOAK_ADMIN_REALM}
  #   healthcheck:
  #     test:
  #       ["CMD", "curl", "-f", "http://localhost:${QUARKUS_HTTP_PORT}/q/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   network_mode: "host"

networks:
  maestroDatabaseNetwork:
