package eu.orchestrator.agent.configuration;


public enum ErrorStatus {

    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_RETRIEVE_IPV4_PRIVATE(-21),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_RETRIEVE_IPV4_PUBLIC(-22),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_RETRIEVE_IPV6(-23),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_OF_CONSUL(-24),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_OF_LOGIN_DOCKER(-25),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_INITIALIZATION_OF_NETDATA_REGISTRATION(-26),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_DOWNLOAD_IMAGE(-32),
    STATUS_TERMINATED_DUE_TO_UNSUCCESSFUL_IMAGE_NOT_FOUND(-33),
    STATUS_TERMINATED_WAITING_FOR_DEPENDENCIES(-41),
    STATUS_TERMINATED_CONTAINER_SERVICE_IS_NOT_RUNNING(-61),
    STATUS_TERMINATED_DUE_TO_BAD_KV_PARSING(-7);

    private int value;

    ErrorStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}