<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>eu.orchestrator</groupId>
    <artifactId>orchestrator</artifactId>
    <version>1.6.0.RELEASE</version>
  </parent>

  <groupId>eu.orchestrator.virtualization-manager</groupId>
  <artifactId>virtualization-manager</artifactId>
  <packaging>pom</packaging>
  <name>Virtualization Manager</name>

  <modules>
    <module>vim-core</module>
    <module>spi</module>
    <module>provider-adapter</module>
  </modules>

</project>